### ISSUE TITLE
Particles change brightness when facing certain directions

### ISSUE THREAD

**Issue by DasGerippe** [VazkiiMods/Botania#3127]
# Version Information
Forge version:  28.1.111
Botania version:  1.11-375

# Further Information
Steps to reproduce:
1. Get a steady source of particles for example through right-clicking sparks.
2. Change the direction you're facing (Yaw and/or Pitch) while watching those particles.
3. While changing your direction you can see that particles change brightness when crossing certain "borders" of your view.

The video below will show what i mean:
![ParticleBug](https://user-images.githubusercontent.com/33161021/71921145-939bdc80-3188-11ea-9000-6ab1daf917c3.gif)

You can see that slightly changing my Pitch, the particles brightness changes when alternating around a certain value. This also happens when changing your Yaw between some values.

**Comment by DasGerippe** [comment]
This bug doesn't occur for me anymore, so if nobody else is having this issue, it might as well get closed.

**Comment by artemisSystem** [comment]
@williewillus this can be closed it seems
