### ISSUE TITLE
Mundane arrows fired from Crystal Bow aren't pickupable

### ISSUE THREAD

**Issue by Alwinfy** [VazkiiMods/Botania#3145]
Steps to reproduce:
1. Grab a Crystal Bow
2. Grab a few arrows
3. Shoot

What I expected to happen: Can pick up arrows fired || won't fire mundane arrows at all

What happened instead: Neither

**Comment by Alwinfy** [comment]
bump

**Comment by Aegide** [comment]
It's not possible anymore to shoot regular arrows with a crystal bow, therefore this issue is fixed.
