### ISSUE TITLE
Wand of Forest rotating Double Chests or Extended Pistons goes funky.

### ISSUE THREAD

**Issue by eutro** [VazkiiMods/Botania#3223]
# Version Information
Forge version:  31.1.25
Botania version:  r11-378.63 but 1.15

# Further Information
Steps to reproduce:
1. Take a Wand of the Forest.
2. Use it to rotate half of a double chest.
3. Observe.
4. Also try this with an extended piston.

What I expected to happen:
The chest not to go all funky.

What happened instead:
![Chest Funkiness](https://user-images.githubusercontent.com/11538216/77748340-190c8b80-7018-11ea-8d2d-97edcc704110.gif)
![Piston Funkiness](https://user-images.githubusercontent.com/11538216/77748891-021a6900-7019-11ea-8c3c-124660cbaeea.gif)

**Comment by cplir-c** [comment]
Reproduced using Botania version 1.19.2-436-FABRIC-SNAPSHOT.
After splitting a chest, on right clicking one of them both halves animate open but only the items from the half you clicked are shown (a single chest worth).

The Wand of the Forest also allows rotating nether portal blocks.

**Comment by artemisSystem** [comment]
We have a tag now for blocks that shouldn't be wand-usable. We should probably do a little cleanup and add some things, it's currently empty. In fact, i realized we probably have a dupe glitch with it. I'll send a patch with some proposed entries.

**Comment by Aegide** [comment]
yeah lmao

![image](https://user-images.githubusercontent.com/43409914/210895353-0f447a2e-6f15-44bd-908a-a337479769f2.png)

**Comment by anoomolu** [comment]
Just adding a few more:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/5361f453-9c00-4249-9c70-c6afa53a77e2)
![image](https://github.com/VazkiiMods/Botania/assets/77850233/52c05045-a63b-4393-898d-a95fedd5ff36)
