### ISSUE TITLE
Trinket Case icon doesn't change when right clicking

### ISSUE THREAD

**Issue by SaikoChan1** [VazkiiMods/Botania#3439]
# Version Information
Forge version:  32.0.108
Botania version:  Botania-1.16.1-403

Steps to reproduce:
1. First step: right click
2. Second step: the box not openened
3. etc...:

What I expected to happen:
the box icon would open when I right click

What happened instead:
it didn't open :(

**Comment by williewillus** [comment]
seems like this texture was never actually used
