### ISSUE TITLE
Update orechid ore weights

### ISSUE THREAD

**Issue by MuteTiefling** [VazkiiMods/Botania#3443]
# Version Information
Forge version:  32.0.108
Botania version:  1.16-403

# Further Information
Link to crash log: no crash
Steps to reproduce:
1. Automate Orechid
2. Wait
3. Keep waiting, because you're not going to get any Fluorite despite it having a forge:ores tag

What I expected to happen: Fluorite to generate occasionally

What happened instead: Generates everything except fluorite

**Comment by williewillus** [comment]
it doesn't generate any `forge:ores`, ores need to be registered to the orechid by telling it how common the ore is

See https://github.com/Vazkii/Botania/blob/54e49c86359f0295c4e1b82fb687f2a774eabf60/src/main/java/vazkii/botania/common/core/handler/IMCSender.java#L21

**Comment by williewillus** [comment]
I'll keep this as a "update the default ore list" issue

**Comment by MuteTiefling** [comment]
Just noticed certus quartz also doesn't generate.

**Comment by MuteTiefling** [comment]
And uraninite, for that matter (from Powah)

**Comment by NillerMedDild** [comment]
This can be closed now I'd say, although the new orechid recipe system has a little issue: https://github.com/Vazkii/Botania/issues/3713

**Comment by Hubry** [comment]
Eh, good defaults are still important to keep, people shouldn't be expected to configure this properly to have a good selection of ores.

**Comment by anoomolu** [comment]
Closing this as the Orechid is now data-driven. https://github.com/VazkiiMods/Botania/issues/4262 has some info in the comments if anyone is unsure how to add recipes.
