### ISSUE TITLE
Refactor delays to not use item ages

### ISSUE THREAD

**Issue by williewillus** [VazkiiMods/Botania#3507]
Right now, Botania overloads vanilla's `age` tag for item entities for its own purposes, such as delaying when items are picked up by flowers. This has caused numerous bugs and very fragile code and magic-constant heavy code throughout the years. [Example](https://github.com/Vazkii/Botania/blob/fd310f6d4f2e41c85f3cdca015296e76936c0b03/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java#L82). Holy magic constants! 

We should port this to a separate variable/tag and migrate all overloads of age to it. Additionally, magic checks such as the above should be pulled into a util class with clear names and documentation, if necessary. Will require extremely careful testing to make sure no behavioural changes are made.

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/b7d88a5f6edbfc26014e6ce0b2d74d6e9e60cbfc
