### ISSUE TITLE
Botania music discs are non-positional, unlike vanilla music discs.

### ISSUE THREAD

**Issue by Moleculor** [VazkiiMods/Botania#3584]
Audio in Minecraft must be mono to be positional. 

Example: Vanilla Minecarts have two audio files. One is mono, for the sound of a cart you are *not* riding moving past you. One is stereo, for when you're riding the cart, and the audio should be all around you. 

Another example are vanilla music discs. Vanilla music discs, when played in game, are positional. If you play a disc and turn to your right, you'll hear the music coming from your left. Moving farther away from the jukebox results in the sound 'moving away' from you, getting quieter. Each audio file for music discs is *mono* for this purpose. Most illustratively, Pigstep was originally mixed as a stereo track, and stereo varieties of it can be played online, but the in-game disc audio is mono *specificially* to maintain a Jukebox's positional audio.

The two music tracks in Botania are stereo. Thus, when you play them in a Jukebox they are played at full, max volume with no positional qualities of any kind. They're the same volume no matter how close or far you are from the Jukebox, and turning to the left or right does not enable you to hear the audio coming from your right or left (the position of the Jukebox). 

Replacing these audio files with mono varieties would fix the lack of positional audio from a Jukebox. However, since I believe these audio files are *also* used during gameplay where the audio should not be positional, I suggest adding two mono varieties of the tracks specifically to only be played when the disc is.

**Comment by williewillus** [comment]
Thanks for the detailed explanation! Unfortunately, the two music tracks already take up a ton of space in the mod jar, so I'm not super keen on doubling the size with mono versions.

I'm thinking perhaps I should just convert them to mono and play them from the beacon position during the boss fight.

**Comment by Moleculor** [comment]
I am no expert on Minecraft modding (only just starting to look in to it), but it may also be possible to simply non-positionally play the mono file in a global sense for the relevant player(s) during the boss fight. It will lack the 'punch' an audiophile might enjoy from having the music in stereo, but it won't have quite the same potentially detrimental 'gameplay experience' impact that positional audio during the boss fight might have. 

But I also could be wrong. 🤷‍♂️
