### ISSUE TITLE
Interface.Optional being gone means many parts of Botania's API are non-viable

### ISSUE THREAD

**Issue by DaedalusGame** [VazkiiMods/Botania#3594]
Implementing some interfaces for compatibility is now impossible for soft-dependencies because it is no longer possible (to my knowledge) to specify that an interface should be implemented conditionally.

What I'd like to suggest is to move interface APIs to [Registry-like types](https://github.com/Da-Technomancer/Essentials/pull/49).
It may also be possible to make some APIs into capabilities, but such a thing is only viable on tile entities as there is to my knowledge no way to attach a capability to a block. 

Advisory on this problem is very welcome.

**Comment by Hubry** [comment]
You could mixin your own classes, if Botania is loaded, now that Forge ships Mixin by default.

**Comment by williewillus** [comment]
Closing as this is mostly mitigated now with usage of forge caps/fabric api lookup. There's probably a long tail of stuff to be migrated but feel free to submit PR's for them and we can get them landed during a major version boundary
