### ISSUE TITLE
IEndoflameHeatable is in the wrong folder

### ISSUE THREAD

**Issue by gamma-delta** [VazkiiMods/Botania#3605]
# Version Information

Forge version:  N/A  
Botania version: 1.16.4-410

## What I expected to happen:

[IExoflameHeatable](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/item/IExoflameHeatable.java) should be in a folder not named `item`, given that there are literally no items involved.

## What happened instead:

It's in `item`.

**Comment by Hubry** [comment]
This really can wait until 1.17 tbh, even if I kinda doubt anyone uses this currently.

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/c111444f44552315ced1a7dd5af7c479d7c7244a
