### ISSUE TITLE
Hopperhocks can suck items from immersive engineering conveyor belts

### ISSUE THREAD

**Issue by LeoBeliik** [VazkiiMods/Botania#3640]
# Version Information
Forge: 36.0.13
IE: 1.16.5-4.2.1-131
Botania: 1.16.4-411

**What I expected to happen:**
Hopperhocks ignore items that are in conveyor belts like magnets do

**What happened instead:**
Hopperhocks suck the items

# Further Information:
I've reported this to IE first and I have been told to report it here :)

![image](https://user-images.githubusercontent.com/11804768/106947761-9198aa00-6709-11eb-888b-0ca8875cfa5c.png)

**Comment by LeoBeliik** [comment]
I guess I'll just close this.

**Comment by ErikaRedmark** [comment]
I'm a bit confused why this was closed with little discussion -- on my old 1.12 server, hopperhocks and endoflames both ignored the contents of conveyor belts until they came off the conveyor. This behaviour was actually very helpful -- hopperhock pulls in an item, and the item is transported somewhere else for some other activity.

With my 1.16.5 server, an attempted build has been rather frustrating to get right as conveyors do not protect the items anymore. Whilst there are ways to modify the build to work around this, the older behaviour makes more sense to me, as it better integrates with transferring an item once you've picked it up.

I would ask why this behaviour was changed -- it seems like the proposed fix would be perfect.

**Comment by williewillus** [comment]
This just fell through the cracks, sorry.

**Comment by LeoBeliik** [comment]
omg
