### ISSUE TITLE
Gaia Guardian does not use the thin arm model

### ISSUE THREAD

**Issue by EnderiumSmith** [VazkiiMods/Botania#3729]
Its quite hard to take a clear screenshot during the bossfight but if you look closely you can see black vertical bars on the arms. This is because the Guardian is using the older player model but im using the newer thin arm model. Since the Guardian copies the player skin it should use the correct model. The giant from twilight forest does the same thing and does use the correct model so it definitely possible. 

![Screenshot from 2021-05-08 16-27-15](https://user-images.githubusercontent.com/20334653/117546384-cb43be80-b032-11eb-9554-fbd1e9fd4b2d.png)

**Comment by williewillus** [comment]
should be fixed on 1.18
