### ISSUE TITLE
[1.16.5] Botania being installed causes WotW dimensions to not render blocks

### ISSUE THREAD

**Issue by Elfinlocks** [VazkiiMods/Botania#3734]
# Version Information
Forge version: 36.1.18
Botania version: 1.16.5-416

# Further Information
Link to crash log: N/A

Mods Installed:
![image](https://user-images.githubusercontent.com/43624750/118375505-08a6cf80-b590-11eb-84f8-20cad2899543.png)

Steps to reproduce:
1. Load game with the above mods
2. Use the "Mars Warp" item to go to WotW mod Mars dimension
3. No blocks will render
4. To confirm this, disable or remove Botania, and try again - blocks will render

What I expected to happen:
I expected blocks in the WotW mod dimension to render

What happened instead:
They did not

Additional Information:
I tried disabling Botania flower generation to see if it was somehow conflicting with WotW mod dimensional worldgen. This did not resolve the issue - blocks continued to not render whilst Botania remained installed.

**Comment by williewillus** [comment]
I honestly don't believe it's Botania at fault here, and since WoTW is closed source, I can't investigate its code. Nothing I can do here.
