### ISSUE TITLE
[1.16.5 Fabric]Rendering Tiny Potato crashes the game

### ISSUE THREAD

**Issue by Neubulae** [VazkiiMods/Botania#3754]
# Version Information
Fabric version:  0.11.3 + API 0.35.0
Botania version:  Latest CI Build(https://github.com/Vazkii/Botania/commit/cc11ed97cb98b4707e78810fbd5611b9b3067cd6)

# Further Information
Link to crash log: https://paste.gg/p/anonymous/b2de8b7d25e541279c5b15e36d2ffd2e
Steps to reproduce:
1. Search for Tiny Potato on Creative

What I expected to happen:

A Tater.

What happened instead:

A Tatercide.

**Comment by williewillus** [comment]
report it on https://github.com/williewillus/botania-fabric-issues/issues
