### ISSUE TITLE
Messenger Lens does not always trigger Mana Detector when fired from Mana Blaster.

### ISSUE THREAD

**Issue by VoilaTada** [VazkiiMods/Botania#3757]
# Version Information
Forge version:  36.1.32
Botania version:  1.16.5-416

# Further Information
Steps to reproduce: 
1. Attach a messenger lens to a mana blaster
2. Place a mana detector next to something redstone activated to more easily see activation, preferably in mid air to avoid interference with the ground.
3. Fire blaster at mana detector

What I expected to happen: Every shot fired within the red square of the face of the detector triggers a pulse from the detector

What happened instead: Only some shots will trigger the pulse.
![2021-06-20_13 35 12](https://user-images.githubusercontent.com/1736774/122683324-74520d00-d1cc-11eb-911c-c07227a59eea.png)

**Comment by Hubry** [comment]
Mana detectors actually work by having no bounding box for mana bursts at all, and triggering if there is a burst in the bounding box. However, bursts are very fast - the default burst already has a speed of 1 block/tick, and the messenger lens *triples* that, so there is a very high chance that the burst simply never exists in that location. 

I think this might be fixable by making detectors have an actual hitbox, though.

**Comment by williewillus** [comment]
fixed in 1.17. The fix won't be in 1.16 because it came alongside another change which breaks world compatibility.
