### ISSUE TITLE
Mana Spreader Not Rendering

### ISSUE THREAD

**Issue by firemaster1294** [VazkiiMods/Botania#3767]
% Version Information
Forge version:  36.1.32
Botania version:  1.16.5-416

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Place a mana pool with a spark above it and a mana spreader nearby
2. Look at the mana spreader through the spark

What I expected to happen: spark shows a mana spreader behind it

What happened instead: when viewing a mana spreader through a spark above a mana pool, the spreader should render - yet it doesn’t from what I can see!

**Comment by williewillus** [comment]
Hard to resolve, unfortunately.
