### ISSUE TITLE
Rod of the Shaded Mesa allows for infinite flight via Minecart, and turbo flight via Llama.

### ISSUE THREAD

**Issue by SleepyEmber** [VazkiiMods/Botania#3771]
# Version Information
Forge version:  36.1.32
Botania version:  Botania-1.16.5-418

# Further Information

Steps to reproduce: 
1. Get in Minecart or Llama (probably any ridable entity)
2. Hold Rod of the Shaded Mesa
3. Spam right/left click
4. Nyoom

What I expected to happen: No nyoom, very sad

What happened instead: Nyoom

[Video Evidence](https://youtu.be/NFHHwMpe0-s)
[Video Evidence 2](https://v.redd.it/l4iyb3ml6na71)
[Video Evidence 3](https://www.youtube.com/watch?v=IajFt4ZGQGg)
[Video Evidence 4](https://youtu.be/el3yedJ40W8)

**Comment by TheGreatCatAdorer** [comment]
Given that the flight this provides is more similar to elytra flight than to the Flugel Tiara and has significant mana cost, I believe this feature should not be removed.

**Comment by SleepyEmber** [comment]
I don’t believe this is stale!

**Comment by williewillus** [comment]
should we just accept this as a feature vote now

**Comment by williewillus** [comment]
ok guess it's a feature now
