### ISSUE TITLE
[1.16.5][Bug] Rod of Shifting crust cannot replace lit redstone ore on right-click

### ISSUE THREAD

**Issue by FizzBuzz3000** [VazkiiMods/Botania#3774]
Title says all. Rod of Shifting Crust cannot replace lit redstone ore on right click. I want to say it's some block state change as no matter how many times you right-click on the block, it *never* gets replaced. The only time lit redstone is replaced is if you left click the block.

**Comment by PoolloverNathan** [comment]
Redstone Ore swallows right-click events, even when it's lit.

**Comment by anoomolu** [comment]
Seems like an issue with vanilla itself.

**Comment by anoomolu** [comment]
Going to close this as it seems like a vanilla issue. For example, fishing rods work when targeting other blocks, but not when targeting (deepslate) redstone.
