### ISSUE TITLE
Binding range sphere not centered at mana pool / spreader

### ISSUE THREAD

**Issue by DasGerippe** [VazkiiMods/Botania#3775]
# Version Information

Forge version:  1.16.5-forge-36.1.32
Botania version:  Botania-1.16.5-418

# Further Information

This bug occurs for generating and functional flowers getting bound to a spreader / pool respectivly. I will only describe the behaviour for functional flowers.

The range for a mana pool in wich flowers can be bound to it is hard-coded as 10 blocks. However, placing a flower 10 blocks away from a mana pool only bounds it to the pool in positive x, y or z directions. In negative x, y, or z directions, the range is only 9 blocks. The resulting sphere in wich flowers can be bound to a pool is not centered at the pool. The same behaviour can be seen when trying to manually bind flowers with a wand of the forest.

Funnily though, when using a Floral Obedience Stick, the sphere in wich flowers will be bound to the pool is shifted in the **opposite** direction (shifted towards negative x, y, and z coordinates).

![2021-07-13_12 35 20](https://user-images.githubusercontent.com/33161021/125439435-9d8e7ae6-e97a-4851-92d2-2b527eee909a.png)

In the image you can see the green circle in wich flowers wil be automatically bound to the pool / can be manually bound to it, as well as the blue circle in wich flowers will be bound to the pool when using the Floral Obedience Stick.

As i said, the same applies for generating flowers and mana spreaders, just with a hard-coded range of 6 blocks.

**Comment by quat1024** [comment]
Somewhat related: When placing a couple of (spreaders/pools) in a line, then placing a parallel line of flowers, the flowers do not always bind to the item they're closest to. Sometimes it's the one 1 block to the left or right. "autobinding" seems to have a strong directional preference.

**Comment by Hubry** [comment]
Fixed in #3831
