### ISSUE TITLE
Floral Obedience Sticks cause desyncs if used in a dispenser

### ISSUE THREAD

**Issue by Carloslionheart** [VazkiiMods/Botania#3782]
# Version Information
Forge version:  36.1.31
Botania version:  1.16.5-419

**Steps to reproduce:**
1. Place a dispenser facing a mana spreader.
2. Insert Floral Obedience stick in dispenser.
3. Fire dispenser.

**What I expected to happen:**
Generating flowers in range should rebind to the mana spreader the dispenser is pointing at.

**What happened instead:**
Nothing happens. Generating flowers remain binded to their previous destination. (Flowers remain unbound if they weren't bound beforehand.)

**Further Information:**
Manual use of the Floral Obedience stick works fine.

**Comment by Carloslionheart** [comment]
I decided to test if this is actually a visual bug, and it seems it is. 

After rebinding the endoflames to another spreader, when Im holding a wand of the forest, they report being bound to their previous target. However when I provide them with fuel, they send mana to their new destination.

**Comment by artemisSystem** [comment]
Seeing the same behavior here, with functional flowers and mana pools. It seems to update visually again after a while, but the flower starts working (since it's getting mana) right away

**Comment by Hubry** [comment]
From some investigation, it seems that the problem is that the binding target never changes on the client if it is only changed serverside. 

The TE update packet sends the position of the bound block, but the actual bound block is not updated there - manual binding works fine because the same binding logic is done clientside.
