### ISSUE TITLE
BlockSpecialFlower's constructor is protected so addons can't instantiate it without subclassing

### ISSUE THREAD

**Issue by quat1024** [VazkiiMods/Botania#3791]
as of 419 (and current HEAD)

https://github.com/VazkiiMods/Botania/blob/944ac4968c186d31faa7fedcdd5b2b2a6fa713f5/src/main/java/vazkii/botania/common/block/BlockSpecialFlower.java#L50

**Comment by Hubry** [comment]
smh my head who did this

**Comment by williewillus** [comment]
wacko
