### ISSUE TITLE
Probably a incompatibility with Optifine

### ISSUE THREAD

**Issue by Leinad112** [VazkiiMods/Botania#3795]
# Version Information: 1.16.5
Forge version:  36.2.0
Botania version:  419

# Further Information

After instaling and deleting Mystical World, Blood Magic and Astral Sorcery mods, the Lexica Botania appears with the missing texture. I thought it can be an incompatibility with some mod and after deleting Optifine it returns to the normal texture. The Optifine version is HD_U_G8.

I tried to re-install al the mods, the whole .minecraft and the bug persist. Mentioned the three mods because before installing them the book seems to be normal.

Here you have a screenshots of the problem: https://imgur.com/a/gstpPmT

What I expected to happen: See the normal texture of the book.

What happened instead: The texture is missing.

**Comment by williewillus** [comment]
yes. Unfortunately, we can't fix it as we have no idea what Optifine does.
