### ISSUE TITLE
Full Crafty Crate keeps trying to match recipes every tick

### ISSUE THREAD

**Issue by Hubry** [VazkiiMods/Botania#3798]
https://github.com/VazkiiMods/Botania/issues/953#issuecomment-899007928_

**Comment by williewillus** [comment]
suggested fix:
* cache "failed match" state in a flag
* bail early if the flag is true
* clear that flag on /reload or when the backing inventory changes in any way

Need a way of clearing the flag every /reload. Maybe a global epoch/generation counter that is incremented each reload, and the failed match flag also stores the value of the epoch when the failure was determined.
