### ISSUE TITLE
Gaia drops nothing if 1-shot

### ISSUE THREAD

**Issue by CaptainPlasma101** [VazkiiMods/Botania#3800]
# Version Information
Forge version:  14.23.5.2854
Botania version:  r1.10-363

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. summon gaia guardian
2. 1-shot it w/ overpowered railgun (not sure about other weapons, maybe sword of cosmos?)

What I expected to happen: gaia guardian drops loot

What happened instead: gaia guardian died w/o dropping loot

**Comment by CaptainPlasma101** [comment]
sry forgot versions are Botania r1.10-363 and forge is 14.23.5.2854

**Comment by CaptainPlasma101** [comment]
nvm overloaded railgun just has so much kb that gaia guardian gets knocked out of arena and cancels fight

**Comment by CaptainPlasma101** [comment]
actually nvm still happens if i do enough dmg not sure if its clipping thru blocks tho

**Comment by Hubry** [comment]
The fact that you could one shot the guardian is the bug here, not that it drops nothing.

**Comment by Hubry** [comment]
Wait, I thought you are on 1.16, but you are on an ancient 1.12 version - barring major bugs, that's not supported anymore.
