### ISSUE TITLE
Multiplayer Only - Flower Pouch deleting flowers, not storing them

### ISSUE THREAD

**Issue by NillerMedDild** [VazkiiMods/Botania#3801]
# Version Information
Forge version:  1.16.5-36.2.2
Botania version:  Botania-1.16.5-419

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Create server with Botania on it
2. Give yourself a Flower Pouch
3. Pick up Botania Mystical Flowers (make sure the pouch is not in your hand)

What I expected to happen:
For the flowers to be picked up by the Pouch

What happened instead:
The flowers disappeared

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3011#issuecomment-899981299

**Comment by williewillus** [comment]
can you try with just botania?

**Comment by NillerMedDild** [comment]
Damnit, the issue does not occur with only Botania and dependencies :P
