### ISSUE TITLE
TileCorporeaCrystalCube compares ItemStack != null in several places

### ISSUE THREAD

**Issue by quat1024** [VazkiiMods/Botania#3802]
This means spurious corporea requests for `ItemStack.EMPTY` get sent through the network (they never match any items), and I think this bit https://github.com/VazkiiMods/Botania/blob/68d9affc68ac0e3499e04c2e7708afebf3de616b/src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaCrystalCube.java#L142-L145 means corporea retainers can send it requests even after you've removed the item from the crystal cube

**Comment by Hubry** [comment]
wtf lmao

**Comment by williewillus** [comment]
1.11 moment
