### ISSUE TITLE
[Cross Mod] [1.16.5] Respect Bucket NBT

### ISSUE THREAD

**Issue by kjj194** [VazkiiMods/Botania#3803]
# Version Information
Forge version:  1.16.5-36.2.1
Botania version:  1.16.5-419

# Further Information
When dropping a bucket of water on a petal apothecary the bucket will be returned without nbt. Quark adds the ability to make a bucket of water and enchant it with infinity to create an infinite water bucket. When dropped on the petal apothecary it returns a plain bucket. 

What I expected to happen: Return a bucket that is still enchanted.

What happened instead: Returned a bucket without the enchantment.

**Comment by Hubry** [comment]
We're almost certainly not going to revisit this as it is pretty minor, and Quark dropped this feature on 1.18 - sorry!
