### ISSUE TITLE
Exoflame boosts Mystical Agriculture furnace burntime incorrectly

### ISSUE THREAD

**Issue by ladylexxie** [VazkiiMods/Botania#3807]
We have received [this issue](https://github.com/AllTheMods/ATM-6/issues/1842) regarding the Exoflame and furnaces from Mystical Agriculture. It seemed to us like an issue from Botania.

If you have any info on it, please let us know!

**Comment by Hubry** [comment]
Looks like the cause is using the recipe's burn time instead of the furnace's burn time.

(the title and issue contents should probably contain some info, btw...)
