### ISSUE TITLE
Flower binding distance is directional

### ISSUE THREAD

**Issue by TheRealWormbo** [VazkiiMods/Botania#3813]
# Version Information
Forge version:  36.2.0
Botania version:  1.16.5-419

# Further Information
Steps to reproduce:
1. Place a mana spreader.
2. With 5 blocks gap each, place a generating flower (on soil or floating) in the north, east, south, west, up and down directions from the spreader.
3. Use the Floral Obedience Stick on the spreader.

What I expected to happen:
Either all or none of the six flowers bind to the mana spreader, since they are all the same distance from the spreader

What happened instead:
Only the flowers in the north, west and down directions (i.e. towards negative X, Y or Z) bind to the spreader. The south, east and up directions refuse to bind, even when using the Wand of the Forest on the individual flowers. The same effect happens when setting up a similar situation with functional flowers, a mana pool and 9 blocks gap.

**Comment by BlueAgent** [comment]
Seems similar to https://github.com/HellFirePvP/AstralSorcery/issues/1784?

https://github.com/VazkiiMods/Botania/blob/c0f1c84cf360b36e98b278a6769efa3970b89622/src/main/java/vazkii/botania/api/subtile/TileEntityGeneratingFlower.java#L263

> The `Vector3i#distanceSq(Vector3i other)` actually gets the squared distance between `this + (0.5, 0.5, 0.5)` and `other`.

> Maybe to fix this, either a helper function for `Vector3i` (which BlockPos extends from), or using `Vector3i#distanceSq(double x, double y, double z, boolean useCenter)` with `useCenter = false`.

**Comment by DasGerippe** [comment]
Duplicate of #3775 and already has a pullrequest (#3789) pending.

**Comment by TheRealWormbo** [comment]
Nice, I'll retract my bug report, then.
