### ISSUE TITLE
[Immersive Engineering] Agricarnation does not accelerate growth of industrial hemp

### ISSUE THREAD

**Issue by dalapo** [VazkiiMods/Botania#3815]
Forge version:  36.2.2
Botania version:  1.16.5-419
IE version: 1.16.5-5.0.3-138

What I expected to happen: Agricarnation accelerates industrial hemp as it does Vanilla crops.

What happened instead: Agricarnation has no effect on industrial hemp.

Looking at the code, it seems to be because industrial hemp extends BushBlock, which the agricarnation explicitly blacklists. Unsure whether or not this is intended behaviour; however, I would expect it to work as it is possible to grow hemp with bone meal.

**Comment by williewillus** [comment]
yeah it's a bit hard to judge with these. BushBlock is a really broad class that everyone vanilla or modded uses for lots of different things, so just letting the agri tick all of them isn't a good idea. Not sure of a good solution.
