### ISSUE TITLE
epic fight armor compatibility

### ISSUE THREAD

**Issue by titaniumman321** [VazkiiMods/Botania#3816]
the render code of botania's armor has to be fixed because it is glitching out when epic fight is installed

**Comment by williewillus** [comment]
Botania's armor models are done in the exact same ways all other entity models in the game are done. Please show a screenshot.

**Comment by titaniumman321** [comment]
![2021-09-12_18 10 11](https://user-images.githubusercontent.com/84505406/132983650-2b80428b-c163-4a78-983b-67d2f97e32a7.png)
![2021-09-12_18 10 26](https://user-images.githubusercontent.com/84505406/132983656-63298592-65f2-436a-bcba-a0d67a5423e5.png)
![2021-09-12_18 10 41](https://user-images.githubusercontent.com/84505406/132983659-68edefb2-984c-45dd-9549-a7227ad82d5b.png)

**Comment by titaniumman321** [comment]
please look into this thankss

**Comment by williewillus** [comment]
Look at the Epic Fight FAQ:

> Q: the mod armor is invisible or looks weird!

> A: Epic Fight Mod uses entity models different from the vanilla Minecraft. So the vanilla armor model has a redesigned model for Epic Fight Mod animation. Custom armors are based on the vanilla Minecraft model, so there could be a visual glitch with Epic Fight Mod.


In other words, Epic Fight is interfering with vanilla (and thus other mods') models on purpose. This is completely on their side, and there's nothing we can do to fix it. Go bother them to make their armors work in a compatible manner.
