### ISSUE TITLE
mana in a bottle kills player without totem

### ISSUE THREAD

**Issue by Petrisis** [VazkiiMods/Botania#3818]
original posted on [quark's issue tracker](https://github.com/VazkiiMods/Quark/issues/3386)

**versions**
minecraft version 1.16.5
forge version 36.2.2
quark version r2.4-316
quark oddities 1.16.3
botania version 419

**log**
https://gist.github.com/Petrisis/708a84c28986cff429f496302e2894bf

**issue**
when using quark's totems for grave handling and dying through use of [Botania] Mana in a Bottle it won't spawn a totem and all items are gone.

**quark config**
https://gist.github.com/Petrisis/dc54f7056ad131bb5325111303b9c73a

**expected behavior**
on dying to whichever cause there should be a totem spawning which helds the players items.

**Comment by Hubry** [comment]
Sadly I cannot reproduce anything with this. There are only 3 events that can change player health:
* tiny explosion... makes an explosion. But it is tiny, it deals damage properly, and only a small amount.
* random health change goes between 1 and 20, which shouldn't kill
* head drop sets health to 1, which shouldn't kill

The one similar case where death would not spawn a thing from a gravestone mod was dying by using the self-sacrifice tool from Blood Magic too much, but that only happened by combining forcing a death and setting health to 0 directly.

Can you provide a more detailed reproduction case?

**Comment by Petrisis** [comment]
did you test with FirstAid mod active? it splits your max health up into separate health for your body parts. if body OR head goes to 0, you die. maybe "set health to 1" did exactly this and caused an undefined death? 
there wasn't even a death message..

**Comment by Petrisis** [comment]
it happened on my modpack [Crashed on Gyrnolia](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia). loading this could be an easier way for you to try to reproduce

**Comment by Hubry** [comment]
I tested with only Quark and Botania :P 

I guess I'll try it tomorrow.

**Comment by williewillus** [comment]
> random health change goes between 1 and 20, which shouldn't kill

I suspect that it's probably this. Likely better to choose a random number between `[1, max_health]`

**Comment by Hubry** [comment]
Bleh, this is where relying on my motivation proves to be working badly.
