### ISSUE TITLE
Multiplayer Only - Flower Pouch deleting flowers, not storing them when using Arclight

### ISSUE THREAD

**Issue by yudonglin** [VazkiiMods/Botania#3820]
# Version Information
Forge version:  forge-1.16.5-36.2.0
Botania version:  Botania-1.16.5-419

# Further Information

#3801 
issue still occur with only Botania and its dependencies, and only occur on Multiplayer server, not a single player world

Potential Solution:
https://github.com/IzzelAliz/Arclight/issues?page=1&q=is%3Aissue+is%3Aopen
Using Pure Forge instead of Arclight 1.0.20 will solve the problem.

**Comment by williewillus** [comment]
Please refer to the following bullet in contributing.md:

> Issues regarding "Bukkit+Forge" servers that are not reproducible with Forge only are not accepted;

This is almost definitely a problem with Arclight and should be brought up on their side. Thanks!
