### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by JustinTheBob** [VazkiiMods/Botania#3822]
-->
# Version Information
Forge version:  1.16.5-36.2.0
Botania version:  1.16.5-419

# Further Information
Link to crash log:https://pastebin.com/TbexMG7M

Steps to reproduce:
1. Install Botania
2. Install Doggy Talents
3. Launch game and look at logs

What I expected to happen:
It not to have "expected" but it does and I don't know if it is because of Botania or Doggy Talents. I have posted this on both.
What happened instead:
It spams with a couple lines of "Expected" here is the small log for just Botania:
https://pastebin.com/hsn1Pfq4

Let me know if this is not a big issue. I just want to know if it is, or if all it does is just spam the log.
Thank you!

**Comment by Hubry** [comment]
Not our issue, they are registering their own content (looks like bed casings?) for materials from other mods under those mods' namespaces instead of their own.
