### ISSUE TITLE
Slime Islands with Garden of Glass Botania skyblock mod

### ISSUE THREAD

**Issue by fatpally** [VazkiiMods/Botania#3823]
Forge version:  36.2.0
Botania version:  1.16.5-419

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step Installed Garden of glass, Tinkers Construct and botania
2. Second step loaded into the pack
3. Inital area around the base no slime islands, moved into 1000x100 increments in each way still no slime islands

What I expected to happen: to see at least one island

What happened instead: nothing

**Comment by williewillus** [comment]
It's a skyblock, why are you expecting anything to spawn? This is intended.
