### ISSUE TITLE
multiplayer server crash with botania mod

### ISSUE THREAD

**Issue by protected22** [VazkiiMods/Botania#3851]
# Version Information 1.16.5
Forge version:  1.16.5-36.2.5
Botania version:  Botania-1.16.5-419

# Further Information
Link to crash log: https://pastebin.com/C0afBx5M
Steps to reproduce:
1. make a forge 1.16.5-36.2.5 server
2. install mods + botania
3. start server
4. see crash log

What I expected to happen:
no crashes. 
What happened instead:
server crashed with crashlog saying botania mod has issues.

**Comment by Hubry** [comment]
Somehow the mixin didn't apply? Post contents of `debug.log` directly, and try running with Java 8.

**Comment by protected22** [comment]
https://pastebin.com/WV1TTk7q

Normally i also use Baubles. But I saw that one isnt up to date (latest is 1.12.2) Do I still need to use that one or is it also possible without?

**Comment by Hubry** [comment]
Welp, that explains everything.
There is an issue where if you don't satisfy all the required dependencies, mixin connectors are not found.

As the CurseForge page for Botania (specifically, the [page for the file](https://www.curseforge.com/minecraft/mc-mods/botania/files/3386883) you are using), you need to add Curios API and Patchouli.
![image](https://user-images.githubusercontent.com/26120076/140430204-d7880ea6-316a-4435-8fa7-bc1fa45c28b0.png)

**Comment by protected22** [comment]
Hi. I tried this by only having Botania, Curios API and Patchouli in my mods folder and it still crashes. 
the server run

I used this versions:
Botania-1.16.5-419.jar
curios-forge-1.16.5-4.0.5.3.jar
Patchouli-1.16.4-53.2.jar

Server console log: https://pastebin.com/aJW1GVvX
debug log: https://pastebin.com/CW6yq8Nf

**Comment by Hubry** [comment]
Your logs don't mention Mixin at all outside of our package names, which means there is something deeply wrong with your installation. Try reinstalling the Forge server, and try launching with Java 8.
