### ISSUE TITLE
[1.17 Fabric] Mana Spreaders consumes crafted lens and don't apply their effects

### ISSUE THREAD

**Issue by Desempregago** [VazkiiMods/Botania#3852]
# Version Information
Fabric version:  0.12.1 + API 0.41.3
Botania version:  420-FABRIC-SNAPSHOT (commit ad3fa1b)

https://user-images.githubusercontent.com/14002834/140437483-f1bf9575-df7e-40fd-90e0-60bedeeec090.mp4

PS: Only legit crafted lens get consumed, but not lens from /give and REI

**Comment by Hubry** [comment]
Looks like having a full inventory is an actually important step for this? I seem to be getting weird behavior with the lens items when removing them, so this is probably a client-server desync and you don't actually have a lens there.

Seems to be related to making lenses stackable.

**Comment by Desempregago** [comment]
that's what I worried about, when getting a stack of lenses, they work, but not individual lenses

**Comment by Hubry** [comment]
I have trouble reproducing this exact effect, I have done a small adjustment that makes lenses behave slightly better in creative (ceaf7351a4cdd84aad8cc107f957bb367118bee1), but I have doubts it will change anything.

I see you are using some other mods. Can you provide a game log file and the modpack/modlist?
Can you try narrowing down the modlist (eg. through binary search) to possibly identify the culprit yourself?

**Comment by Desempregago** [comment]
Log file doesn't say nothing I should be aware of at the time I apply a lens on a spreader.
This is my modlist
![image](https://user-images.githubusercontent.com/14002834/140561810-67d0d0ad-efff-4610-9218-85580a89e55a.png)

**Comment by Desempregago** [comment]
I will try binary search in a few minutes

**Comment by Desempregago** [comment]
also, from my testings the lens only apply if they're part of a stack (more than one lens in the same stack, as soon as the stack drops to 1, lens don't apply anymore and instantly vanish)

**Comment by Desempregago** [comment]
**UPDATE**: I tested with ONLY Botania (and trinkets + patchouli as dependencies) and I reproduced it.

**Comment by Hubry** [comment]
Cannot reproduce. Please try on current commit anyways.

**Comment by Desempregago** [comment]
will do.

**Comment by Desempregago** [comment]
Looking at the commits, I'm not sure what got changed that could affect the lenses, but they are working now. Commit b9ac19

**Comment by Desempregago** [comment]
Gonna close the issue. Thanks for taking your time to sort this out.
