### ISSUE TITLE
[1.16.5][Bug] Spark visual bug

### ISSUE THREAD

**Issue by Lalo611** [VazkiiMods/Botania#3854]
# Version Information
Forge version:  36.2.8
Botania version:  419

If you look closely at a spark you can easily notice that you can see though it, just a minor visual bug
![Sin título](https://user-images.githubusercontent.com/69506035/141610905-aa6a63de-afa0-4eba-98bc-afb4fc9a6a41.png)

**Comment by Hubry** [comment]
Use Fabulous rendering. I don't think we can really fix this on fast/fancy.
