### ISSUE TITLE
Manatide bellows can cause vanilla furnace to take infinite time to cook items

### ISSUE THREAD

**Issue by bloche1871** [VazkiiMods/Botania#3855]
# Version Information
Forge version:  net.minecraftforge:36.2.8
Botania version:  Botania-1.16.5-420

# Further Information
Seems maybe related to #3807 but happens with the vanilla furnace.
![bug](https://user-images.githubusercontent.com/1149090/141658927-05c64379-7b84-468e-8b5e-5757a9ecbf7a.png)

What I expected to happen: Item cooks faster when using bellow.

What happened instead: Item never finishes cooking and progress bar goes off infinitely.

**Comment by Hubry** [comment]
what the heck have i done wrong this time

**Comment by Hubry** [comment]
Oh, I missed the `-1` somehow.
