### ISSUE TITLE
Overgrowth seeds not dropping

### ISSUE THREAD

**Issue by zookeper** [VazkiiMods/Botania#3857]
# Version Information
Forge version:  36.2.6
Botania version:  1.16.5-419

1. First step Enchant sword like so.
![image](https://user-images.githubusercontent.com/4263760/141697907-81babdb1-a526-4377-9e9f-bfc105cb559c.png)

2. Second step, Kill Gaia Guardian 2
3. Watch the seeds not drop.

What I expected to happen:
Overgrowth seeds to drop

What happened instead:
Tons of other loot besides overgrowth seeds

I'm not sure if its an enchant screwing with the drops but in the 126 Gaia kills I have received only 12 seeds and that was in the beginning.

With this many mods and drops like this it would be wise to check your code and make sure that no other mods are conflicting with your drops.

At this point I'm about to scrap even using this mod because in that time I literally have Unobtainium bees so what's the point of soil that barely grows?

**Comment by williewillus** [comment]
....what exactly are you expecting? You're using a ton of mods that interact in unknown ways. In base Botania, it is simply a loot table roll. It's not broken there.

If you really wanted to track it down, start removing mods and rolling the loot table by hand using /loot, otherwise there's not much to do here.

**Comment by Hubry** [comment]
Rolling the loot table by hand won't work because it will lack the player context and drop literally nothing, actually.

12 seeds does sound awfully low, since it is a 25% chance to get one - if no other loot is affected, are you sure there isn't something like a global loot modifier that cuts seed chances in all loot tables?

**Comment by zookeper** [comment]
I don't believe so. I have asked the owners if  the loot table was changed and they have not.

Also. I'm not "expecting" anything, what I would like is for things to work and I'm not sure what's causing the issue, Honestly would be less work for the dev or someone who had access to go hmmm. maybe I didn't code the draconic evolution enchant or maybe the looting level is too high? or maybe its the sword from mahou? at least i took a snippet of the weapon and the only real reason I posted this is because I thought maybe my experiences with end game botania would improve for everyone else and me. It's a fun mod, I love it a lot, it's just. get to a certain point and the only way to get the seeds is to farm a buggy boss that spawns mobs inside the ground? (on that note, force move gaia to the top of the beacon on mob spawn phase) and please enable woot farm to drop overgrowth seeds.... or another mod. i would be happy with 5-10% chance reduction for those methods or even more because it's (automated)

And well. my input is good because I play the modpack a lot and yeah a lot of people have botania installed into their packs with multiple mods, it's not just me having this issue either it's apparently been posted before.

Regardless if this is a repost what I said earlier is important and should be taken constructively and not personally.

**Comment by Hubry** [comment]
First of all, what is the modpack you are playing? I can't try to reproduce this or investigate further as I lack this info.

> I have asked the owners if the loot table was changed and they have not.

It didn't have to be the server owner. It could be the modpack author, or another mod! And this is surprisingly easy to do.  
With CraftTweaker, all it takes to make the seeds not drop from *any* loot table is
```zenscript
import crafttweaker.api.loot.modifiers.CommonLootModifiers;
loot.modifiers.registerUnconditional("no_seeds", CommonLootModifiers.removeAll(<item:botania:overgrowth_seed>);
```
You mentioned "I have received only 12 seeds and that was in the beginning." A modpack update changing a script to make the seeds unobtainable for some unknown reason, after you got your 12th seed?

> the only way to get the seeds is to farm a buggy boss that spawns mobs inside the ground? 

That should be an an another issue report, and it isn't actually the only way - they are rare dungeon loot in dungeons, mineshafts, desert and jungle temples, and strongholds. (the loot modifier above would still nuke them).

Lastly... what is your use for large amounts of overgrowth seeds? Most uses of them can be replaced by just using two flowers of the same type instead.

**Comment by zookeper** [comment]
The part got cut out at the top, not sure why, it should say ATM 6 1.8.9 above the forge version

**Comment by zookeper** [comment]
After contemplating a bit I feel as if it's draconic evolutions enchant that is breaking it because it's the only mod that resets the loot modifier.

**Comment by zookeper** [comment]
I'm not sure why atm 6 would drop the loot from that when its designed to be mid game. after you get close to the end is when you can start making dimensions and at that point you no longer need any other resource gen.

**Comment by zookeper** [comment]
I would test this further but my base got deleted because I activated Ritual of the martyr [woot] and it caused the server owner to delete my entire base.... even still if i sign on the server just insta crashes. 

You know, im not even sure why im posting this, i just feel that lately other mod makers troll people including other mod makers in these packs and just blame it on server owners or the person running the game.

Why on earth should this be okay? 

If car companies said whatever to safety in vehicles when they built them like some of these packs have then most of the people who drive would be dead.

**Comment by zookeper** [comment]
and about my gaia comment. i loved the fact that I had to setup an area to fight it. that was different than anything in minecraft. keep that!! dont change it!! <3
