### ISSUE TITLE
[Bug]: Non-Empty Mana Pools in Botania 1.16.5-420 Breaking Shaders

### ISSUE THREAD

**Issue by syminical** [VazkiiMods/Botania#3867]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

1.16.5-420

### Modloader version

Forge: 36.2.9

### Modpack info

https://www.feed-the-beast.com/modpack/ftb_oceanblock

### The latest.log file

https://symys.org/latest.txt

### Issue description

I added OptiFine_1.16.5_HD_U_G8_MOD.jar to the pack's mods folder so that I could use shaders.
I'm using ComplementaryShaders_v4.2.2, but it also affected Sildur's Vibrant Shaders v1.30.

Botania pools (all available pool types) are doing something weird to my shaders, specifically when they have mana in them.
As soon as there is mana in the pool my shader acts up, and I even get some OpenGL errors (1282) sometimes in the chat. In Complementary shadows seem to 'follow' me around when I move, and in Sildur it adds a weird discolouring effect around me as I move.
When I break the pool the shaders go back to normal. Empty pools don't affect the shaders.

I don't get the OpenGL errors from Sildur, but it still has a visual bug. You may have to move around a bit to find an event that sets off the OpenGL errors, but the visual bug is instantaneous. 

Covering up the non-empty mana pool with blocks doesn't stop the shader from breaking.
Walking out of render distance, or maybe the chunk, fixes the shader.

### Steps to reproduce

1. Install OceanBlock.
2. Install optifine. (Run the .jar downloaded from optifine's website and extract the mod .jar, then put that into the modpack's mod folder).
3. Select and use one of the shaders.
4. Make a new ocean block world. (The effect is most noticeable in bright sunlight.)
5. Put down any mana pool.
6. Throw a charged mana tablet into the pool.
7. Walk around.
8. Break the mana pool.
9. Walk around.

### Other information

latest.log was too big for pastebin

**Comment by Hubry** [comment]
Report to shaderpack author or to Optifine, we don't support using those.
