### ISSUE TITLE
 [Fabric] crash with newer FABRIC Loader Version 0.12.x

### ISSUE THREAD

**Issue by MSandro** [VazkiiMods/Botania#3869]
### Mod loader

Fabric

### Minecraft version

1.17.1

### Botania version

Botania-1.17.1-421-FABRIC

### Modloader version

Loader 0.12.5 API 0.43.1

### The latest.log file

https://gist.githubusercontent.com/MSandro/3884988ddec8dfb669414f62346ee87b/raw/ee75382ce4efa7100c2d736782969ceacb6672ff/latest.log

### Issue description
I am currently testing botania bevore I include it in my Modpack Sky FABRICation 2. I plan to update the Fabric API in the next version from 0.11.7 to 0.12.5 but there seems to be problems with botania now.
when I join the singe player workd MC is crashing.
![image](https://user-images.githubusercontent.com/10937159/143772317-6f6b7577-2155-42be-b7b3-d463bef3e310.png)
I just have this few Botania blocks in my world. This screenshot was made with an MC instance with older Fabric Loader 0.11.7

**Comment by Hubry** [comment]
Post the crash report too, please

**Comment by MSandro** [comment]
https://gist.githubusercontent.com/MSandro/36dbb731032f3892e5af6e8a31f8e550/raw/75c381b00bd19b26a5ae5cefb248b2ce51f8327d/crash-2021-11-29_11.31.54-server.txt

**Comment by Hubry** [comment]
Ugh, it's advancement sorting. Try just starting the game again?

**Comment by Hubry** [comment]
Try adding https://www.curseforge.com/minecraft/mc-mods/advancements-debug

**Comment by MSandro** [comment]
Thank you very much, it now doesn't crash anymore.
