### ISSUE TITLE
[Typo] Sojourner's Sash is misspelled

### ISSUE THREAD

**Issue by rsaihe** [VazkiiMods/Botania#3871]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

1.16.5-420

### Modloader version

Forge 36.2.19

### The latest.log file

https://www.toptal.com/developers/hastebin/ilirolisom.yaml

### Issue description

The Sojourner's Sash is incorrectly spelled as "Soujourner's Sash".

**Comment by Hubry** [comment]
Amazing that nobody noticed this for 7 years, and I never even thought this could be incorrect. Thanks!
(Also I had to fix my fix in https://github.com/VazkiiMods/Botania/commit/ce4e5c1da316626b2f3dcb78b54b30ce7fbccbc.)
