### ISSUE TITLE
Crash on SP Join World // DIsconnect from Server

### ISSUE THREAD

**Issue by red2blue** [VazkiiMods/Botania#3872]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

Latest

### Modloader version

0.12.8

### Modpack info

https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2

### The latest.log file

https://pastebin.com/hKnH3eSm

### Issue description

Creating or joining a single player world crashes the game immediately. 

Joining a server disconnects you immediately.

### Steps to reproduce

Install Botania
join world

### Other information

Due to vazkii.botania.common.Botania.registerCommands(Botania.java:283)

**Comment by Frost993** [comment]
**+1**  Removed all mods and still occurs if that was going to be a question from the dev.

### Same Crash Report:
https://pastebin.com/A0av7q6q

**Comment by ImAK9** [comment]
I second this: https://paste.alloffabric.com/anarudotac.yaml

**Comment by DillonSimeone** [comment]
+1, happening to me too.

Lastest Log: https://pastebin.com/vwjpQ2BQ
Crash Log: https://pastebin.com/n5GYhKuS

**Comment by Hubry** [comment]
Why the heck does Fabric not ship the datagen api to users...

Anyways: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/botania-fabric/files/3551435) under review
[This build from Jared's CI](https://ci.blamejared.com/job/Botania/view/tags/job/release-1.18-424-fabric/lastSuccessfulBuild/artifact/build/libs/Botania-1.18-424-FABRIC.jar) is the exact same file

**Comment by DillonSimeone** [comment]
@Hubry Oddly, this didn't fix the issue on my side. Still crashing when attempting to join worlds, both old and new. 

Crash log: https://pastebin.com/2NDRrQdP
Lastest log: https://pastebin.com/9SPf8QjH

I'm 100% sure that I'm using the Botania 1.18-424-FABRIC download you linked us to, not Botania 1.18-423-FABRIC. It shows that in the log too. I visually confirmed that it's that one in the mod folder, and from ingame.

![image](https://user-images.githubusercontent.com/21962421/144842913-45d6aa33-f93f-41ce-8612-d174170a8607.png)

**Comment by Hubry** [comment]
@DillonSimeone that's a distinct crash with `modify-drops-api`, unrelated to this.

**Comment by DillonSimeone** [comment]
Ahh, confirmed. A clean fabric 1.18 game with just Botania and its dependencies loaded without any problems. It's a mysterious mod conflict on my side, apologies.

**Comment by DillonSimeone** [comment]
After some manual troubleshooting, I've tracked it down to this one mod.

https://www.curseforge.com/minecraft/mc-mods/chest-cavity

I guess that the mod attempting to make a chest cavity (and organ drops) for the Guardian of Gaia broke everything! Thank you.
