### ISSUE TITLE
Mixin conflict with Enhanced Celestials

### ISSUE THREAD

**Issue by AeiouEnigma** [VazkiiMods/Botania#3873]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

1.18-423

### Modloader version

Fabric Loader 0.12.8, Fabric API 0.44.0

### The latest.log file

https://gist.github.com/AeiouEnigma/7a74e5242860497f9cd2532bea78ed9a

### Issue description

When using both Botania and Enhanced Celestials, a crash occurs on startup due to both mods using @ModifyConstant mixin methods to affect the size of the moon. [Here](https://github.com/CorgiTaco/Enhanced-Celestials/blob/761b7a520f6eb2a665f0bfbf3d7e30073ea3aa7a/src/main/java/corgitaco/enhancedcelestials/mixin/client/MixinWorldRenderer.java#L47) is the relevant method that Enhanced Celestials uses. I'm not sure whether this will be straightforward to resolve, but hopefully there's something that can be done about it.

### Steps to reproduce

Install both mods and launch the game.

**Comment by AeiouEnigma** [comment]
I've also opened [an issue](https://github.com/CorgiTaco/Enhanced-Celestials/issues/88) on the Enhanced Celestials github.

**Comment by Hubry** [comment]
This needs to be solved by manipulating the pose stack to achieve the same result, but I always forget to do this. 

Fun fact: this also conflicts with a Botania addon in 1.16.
