### ISSUE TITLE
Mixin conflict with Chest Cavity

### ISSUE THREAD

**Issue by AeiouEnigma** [VazkiiMods/Botania#3875]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

1.18-424

### Modloader version

Fabric Loader 0.12.8, Fabric API 0.44.0

### The latest.log file

https://pastebin.com/nGeLt8E8

### Issue description

Installing both Botania (Fabric) and Chest Cavity results in a crash upon loading a world. Botania's MixinLootTable class targets the filterDisposables method which Chest Cavity's ([modify-drops-api](https://github.com/Tigereye504/modify-drops-api/blob/857d48689334239b000ba060812062bff66e75ec/src/main/java/net/tigereye/modifydropsapi/mixin/LootTableGenerateLootMixin.java#L18)'s?) LootTableGenerateLootMixin class modifies.

I've opened [an issue on Chest Cavity's github](https://github.com/Tigereye504/chestcavity/issues/56) as well.

Hopefully a solution can be found.

### Steps to reproduce

1. Install Botania and Chest Cavity
2. Minecraft will crash upon trying to load a world

### Other information

Chest Cavity version: 2.13.3

**Comment by Dustalis** [comment]
I'm experiencing the same issue on world load.
[crash-2021-12-07_00.13.06-client.txt](https://github.com/VazkiiMods/Botania/files/7665935/crash-2021-12-07_00.13.06-client.txt)

**Comment by Tigereye504** [comment]
Fixed in Chest Cavity 2.13.5
