### ISSUE TITLE
[Fabric] No real-time data updates to client

### ISSUE THREAD

**Issue by kohanis** [VazkiiMods/Botania#3876]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

1.18-424

### Modloader version

Loader 0.12.8 + API 0.44.0

### The latest.log file

-

### Issue description

Data about the level of mana, rotation, items inside, etc. are updated only when the world is reloaded (like saving and loading, connecting to a server, or moving to another dimension and back) and never in real time.
No problems with sounds and "crafts" itself, though

**Comment by williewillus** [comment]
fixed in next version (see ecce709)
