### ISSUE TITLE
If multiple guns and multiple lens are combined, some of them will be lost

### ISSUE THREAD

**Issue by Kanbe-Kotori** [VazkiiMods/Botania#3877]
### Mod loader

Forge

### Minecraft version

every

### Botania version

every

### Modloader version

every

### The latest.log file

every

### Issue description

See ManaGunLensRecipe.java. You should have judged if there was only one gun and one lens. I mean, should you write codes like...
if (stack.getItem() instanceof xxx...) {
**if(foundGun)**
**return false;**
else
foundGun = true;
}

### Steps to reproduce

1. Put multiple guns and multiple lens into the craft table
2. Craft
3. You get ONE gun, and the remaining will be lost

**Comment by williewillus** [comment]
Please fill out the version fields properly.

**Comment by Kanbe-Kotori** [comment]
> Please fill out the version fields properly.

Every version I tested contains this bug

**Comment by williewillus** [comment]
> Every version I tested contains this bug

list out the ones you tested then. Even that would be more useful than "every", which is completely useless information.

**Comment by Hubry** [comment]
Fixed for 1.18 builds.
