### ISSUE TITLE
Visual issue

### ISSUE THREAD

**Issue by dummysnake** [VazkiiMods/Botania#3878]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

v1.18-424

### Modloader version

0.12.8

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

### The latest.log file

https://pastebin.com/RkV197hS

### Issue description

GUI is broken, mana level bar doesnt refresh visually when i input more mana into the mana pool, and the runic altar doesnt update whenever i put any items in it, and it doesnt update to show the progress of the rune either when using the wand, the progress remains the same even though mechanically it still works properly in the background, the only way to refresh it visually to know where in the process i still am is to close the session and reopen it which is very tedious

**Comment by williewillus** [comment]
update to 425
