### ISSUE TITLE
Mana bursts and some other particles not showing

### ISSUE THREAD

**Issue by Fade-Alchemist** [VazkiiMods/Botania#3879]
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

425 Fabric

### Modloader version

Fabric 0.12.11

### The latest.log file

n.a

### Issue description

Many particles are missing or invisible. Notable ones so far: 

1. Mana bursts from spreaders.
2. The effect for when an item is being converted via the pure daisy (like rock to living rock for example)
3. The particles above the generating flowers that show that they are working (like the endoflame and exoflame)

There are probably others, but these are the ones I have noticed thus far. 

### Steps to reproduce

Attached is the collection of mods I am playing, note that Sodium is part of the pack, but is inactive. (I turned it off to test if this was the cause of the missing particles, it was not).

To reproduce: Guilty pool connected to a spreader pointing at another empty pool several blocks away. 

The expected behavior: Green beams of mana traveling to the empty pool to fill it. 

The actual behavior: While the pool will fill, there is no visual representation of the mana being shot to the pool. 

### Other information

[Botania 1.18.zip](https://github.com/VazkiiMods/Botania/files/7708651/Botania.1.18.zip)

**Comment by williewillus** [comment]
can you try with botania alone? fabulous or fancy?

**Comment by Fade-Alchemist** [comment]
Sure, I will give that a shot, one moment.

**Comment by Fade-Alchemist** [comment]
I just tried it alone with fancy and Fabulous and it works. One of the other mods must be conflicting? 

I would have bet it was sodium....but I did a test with it disabled with no positive results.  Anyway, with the mods included I tried it on Fancy and Fabulous settings with the same result- no visible mana bursts

**Comment by Hubry** [comment]
If you have Entity Culling in there, this is a known issue.

**Comment by Hubry** [comment]
Okay, I found the pure daisy part, that's also related to block entity syncing changes in Fabric API (I forgot to accomodate flowers for this... I am a bad maintainer lmao) but at least it is less severe than the rest of this.

Mana bursts are definitely the fault of entity culling though.

**Comment by Hubry** [comment]
Closing this as I fixed what is in my control, and reported the culling issue to them as it is kinda out of my control (outside of adding soft overrides to our code...) (https://github.com/tr7zw/EntityCulling/issues/50).

Add `botania:mana_burst` to their ticking whitelist to prevent this, hopefully it will be the default soon.

**Comment by Fade-Alchemist** [comment]
I just did a test of my own with Entity Culling Fabric/Forge (by tr9zw) project id 448233 turned off and the mana spark particles returned. Interestingly enough the version of Entity culling used by Sodium does not seem to have a deleterious effect on the appearance of mana sparks. So Sodium = Ok, Entity Culling Fabric/Forge (by Tr9zw) = no go. 

Thanks for all the kind help ya'll!
