### ISSUE TITLE
Suggestion: Horn of the Canopy clears vines

### ISSUE THREAD

**Issue by darchitectlp** [VazkiiMods/Botania#3881]
### Mod loader

Forge

### Minecraft version

1.16.5

### Botania version

Botania-1.16.5-420

### Modloader version

Forge 36.2.2

### The latest.log file

https://pastebin.com/qStcSkRK

### Issue description

I thought one of the Botania horns used to clear vines? But it's been awhile since I've played. Would be nice to have that functionality. I know the Winter Shears from Reliquary can do it; super useful.

Thanks!

**Comment by williewillus** [comment]
sure, why not

**Comment by Hubry** [comment]
Added in 1.18 builds
