### ISSUE TITLE
Botania mana pylon crashing with REI

### ISSUE THREAD

**Issue by irunatbullets** [VazkiiMods/Botania#3882]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18-425-FABRIC

### Modloader version

0.12.11

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

### The latest.log file

https://paste.alloffabric.com/xaravavamo.yaml

### Issue description

A player in on our official AOF5 server reported that searching in REI caused this crash. I checked with shedaniel whether it was an REI or Botania thing, but have posted it here while waiting for a reply just in case.

### Steps to reproduce

1. Open your inventory
2. Type `bo`
3. Crash

### Other information

I have not had time to try reproducing this yet, and have not really heard anyone else mentioning this issue yet (which is a bit odd).

**Comment by Hubry** [comment]
Of course there is Dashloader added there...

**Comment by irunatbullets** [comment]
I didn't notice that user had added Dashloader. Thanks for you help with them though.
