### ISSUE TITLE
Botania creative tab title is difficult to read

### ISSUE THREAD

**Issue by rsaihe** [VazkiiMods/Botania#3884]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18-425-FABRIC

### Modloader version

Fabric: Loader 0.12.12 + API 0.44.0

### The latest.log file

https://www.toptal.com/developers/hastebin/udosazufic.yaml

### Issue description

In the Fabric 1.18 version of Botania, the title of the creative tab is quite difficult to read, having very low contrast compared to the surrounding green bar:

![](https://user-images.githubusercontent.com/50564448/146689921-7753cca3-89fb-4bdf-9f1f-2196ed440229.png)

However, in the Forge 1.16.5 version of Botania, the title of the creative tab is a much more readable color:

![](https://user-images.githubusercontent.com/50564448/146689942-18255a24-d4b4-4381-babc-33a63e38bb78.png)

**Comment by Hubry** [comment]
Looks like a single line got lost in porting.
