### ISSUE TITLE
Fabric Garden of Glass skybox rendering poorly

### ISSUE THREAD

**Issue by jpeterson2** [VazkiiMods/Botania#3886]
### Mod loader

Fabric

### Minecraft version

1.17.1

### Botania version

1.17.1-422-FABRIC

### Modloader version

Fabric Loader 0.12.12/API 0.45.0

### The latest.log file

https://gist.github.com/jpeterson2/7a2b9ac16aa9c2a70c4b3aaf8960ab15

### Issue description

The Botania GoG skybox doesn't render properly on Fabric 1.17.1
![2021-12-22_15 59 32](https://user-images.githubusercontent.com/44014143/147168775-bc45d30e-8666-4d3f-924e-e6a552cad398.png)
What I expected:
The GOG skybox to render with all the planets and rainbows.
What happened instead:
Smeary squares rendered where the planets and bands should be.

![2021-12-22_16 30 31](https://user-images.githubusercontent.com/44014143/147170021-a2ec09be-b211-43a4-ac65-5086ca4368ae.png)
The issue also occurs on a fresh 1.18.1 install.

### Steps to reproduce

1. Install Botania on Fabric on 1.17
2. Install garden of glass on Fabric on 1.17
3. Load a new world of type Garden of Glass
4. Look At The Sky

**Comment by Hubry** [comment]
Known: https://github.com/williewillus/botania-fabric-issues/issues/102

This is a bit on the backburner as we both are bad at rendering

**Comment by williewillus** [comment]
I'm pretty sure what causes this (we use a vanilla method that sets a shader without texture support), but just haven't gotten around to fixing it.
