### ISSUE TITLE
Mixin-related crash regression build 425 → 426

### ISSUE THREAD

**Issue by dequbed** [VazkiiMods/Botania#3888]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-426-FABRIC

### Modloader version

Loader 0.12.12; API 0.45.0

### The latest.log file

https://paste.ee/p/8gV0c

### Issue description

When trying to load the (curseforge) build 426 of Botania it failes to apply a Mixin, crashing right after opening the Minecraft window itself. Using build 425 does not crash with the exact same configuration.

Crash is observed with both Fabric-API 0.45.0 and 0.44.0

### Steps to reproduce

1. Install Botania build 426, Fabric API, Patchouli & Trinkets
2. Start the game :P

### Other information

SHA256 hash of related Botania files:
```
a429cb41ffd3015c111d76384ca2e596972ee033097925903e90b72f114e2476  Botania-1.18.1-426-FABRIC.jar
f8affe8dfddd9c5f7872b9527c73b105e56c8339d941c39529f2dbdaeb0b496c  Botania-1.18-425-FABRIC.jar
```

**Comment by mortche** [comment]
I can add that this problem was also present in all snapshots of version 1.18.1-426.

**Comment by mortche** [comment]
I can also add that it works fine on server, it just crashes the client.

**Comment by Hubry** [comment]
i am a terrible modder

**Comment by Hubry** [comment]
Build 426 archived, grab [build 427](https://www.curseforge.com/minecraft/mc-mods/botania-fabric/files/3578081) instead (not approved yet, as of writing this). My apologies for the issue.

**Comment by vrda** [comment]
Still crasing on 427

**Comment by vrda** [comment]
https://paste.ee/p/1AHnv

**Comment by Hubry** [comment]
@vrda That crash report lists build 426 and a... development build of Patchouli? A Forge build, perhaps? That's not this issue.

You want to delete that old Botania and grab [this Patchouli build](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric/files/3565996).

**Comment by dequbed** [comment]
> i am a terrible modder

You're fine, we all make mistakes from time to time. Thanks for fixing this issue this quickly!

**Comment by vrda** [comment]
ok im retardet wrong mod its fine now
